# Generated by Django 4.2.7 on 2025-09-07 23:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('images_urls', models.JSONField(blank=True, default=list)),
                ('images_url', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=100, choices=[
                    ('Dégradation', 'Dégradation'),
                    ('Équipement cassé', 'Équipement cassé'),
                    ("Problème d'accès", "Problème d'accès"),
                    ('Sécurité', 'Problème de sécurité'),
                    ('Propreté', 'Problème de propreté'),
                    ('Autre', 'Autre'),
                ], default='Autre')),
                ('etat', models.CharField(max_length=100, choices=[
                    ('Nouveau', 'Nouveau'),
                    ('Vérification', 'En vérification'),
                    ('En maintenance', 'En maintenance'),
                    ('Maintenance effectuée', 'Maintenance effectuée'),
                    ('Rejeté', 'Rejeté'),
                    ('Fermé', 'Fermé'),
                ], default='Nouveau')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, null=True, help_text="Notes internes pour l'administration")),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='installations.installation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='authentication.userauth')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to='authentication.userauth', help_text='Admin qui a traité le signalement')),
            ],
            options={'ordering': ['-date']},
        ),
    ]
