services:
  - name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env:
      DATABASE_URL: ${{ Postgres.DATABASE_URL }}

  - name: db
    image: postgres:15-alpine
    env:
      POSTGRES_USER: sportadmin
      POSTGRES_DB: sport
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: